use_frameworks!

target 'CMActionSheet_Example' do
  pod 'CMActionSheet', :path => '../'

  target 'CMActionSheet_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
